rdkcentral/BartonCore

.github/workflows/action-constants.yaml
.github/workflows/check-copyright-headers.yaml
.github/workflows/check-pr-title.yaml
.github/workflows/run-tests.yaml

We're public now - we don't need it.

fix(ci): No longer depend on secret for CI checkout

---

core/src/subsystems/matter/test/CommissionableDataProviderTest.cpp
testing/lsan.supp

We were overzealously suppressing glib leaks which backfired on our own ability to detect leaks with ASAN-enabled compilations. This commit refactors the LSAN suppression file to include glib again, suppressing surgically what things can pop up in our integration tests that are outside our control.
This commit also fixes a leak in recent CommissionableDataProviderTest that was exposed as part of the suppressions fix.

fix: Fix LSAN suppressions to detect leaks again

---

.github/workflows/action-constants.yaml
.github/workflows/run-tests.yaml
docker/Dockerfile.devcontainer
docker/build.sh
docker/compose.devcontainer.yaml
docker/compose.yaml
docker/setupDockerEnv.sh
dockerw

We found after the repository went public that docker images are not
able to hosted publicly within the organization. This caused build
breaks since outside users were not able to pull the image and also
prevents CI from running in forks.
To restore functionality:
- add logic to ensure the image is built if it cannot be found locally
- in CI, add logic to see if the image cannot be pulled, indicating a
fork, and if so, build the image accordingly
Additionally, the image repository name is duplicated in many places. To
reduce this duplication, have one source of truth for this value within
`docker/setupDockerEnv` to allow for sourcing by the various Docker
processes.
Refs: BARTON-250

build: ensure image is built by default

---

config/cmake/options.cmake

Stacked PRs:
* #19
* #18
* __->__#17
--- --- ---
We added DefaultCommissionableDataProvider for both dev and as the
default provider but forgot to add it to the default value of the
BDS_MATTER_PROVIDER_IMPLEMENTATIONS config option. Likely a consequence
of merge conflict handling at the time.

build: Add missing provider implementations

---

docker/setupDockerEnv.sh
hooks/install.sh
hooks/post-checkout

Add post-checkout hook to warn users when running in outdated containers after git operations like pull/checkout. This ensures developers are notified when their development environment needs to be rebuilt due to Docker image version requirements changing.
Also enhance Docker tag management to automatically use the highest versioned git tag (docker-builder-*) for image versioning, ensuring builds use compatible toolchains while handling custom tags gracefully. The system warns users when custom tags are based on outdated builders and provides guidance on updating, maintaining consistent environments across the team.
Refs: BARTON-246

build: improve Docker tag management and container warnings

---

core/src/subsystems/matter/providers/BartonCommissionableDataProvider.cpp

We should not be ever referencing BartonProjectConfig.h or any equivalent header. This header is used by the matter sdk build to configure certain things in the matter sdk and any given client may or may not create one or even by some other name. It should be opaque to BartonCore code.
Luckily the only reference was an unused header include.
Refs: BARTON-252

fix: Don't reference BartonProjectConfig.h

---

core/CMakeLists.txt
core/test/src/deviceCommunicationWatchdogTest.c

This change adds the unit tests for the functions present in deviceCommunicationWatchdog.c/h file.
Refs: BARTON-242

test: Unit tests for deviceCommunicationWatchdog

---

api/c/public/device-service-client.h
api/c/public/events/device-service-zigbee-remote-cli-command-response-received-event.h
api/c/src/events/device-service-zigbee-remote-cli-command-response-received-event.c
api/c/test/device-service-client-test.c
api/c/test/events/device-service-zigbee-remote-cli-response-received-event-test.c
core/CMakeLists.txt
core/src/event/deviceEventProducer.c
reference/src/eventHandler.c

This commit adds BDeviceServiceZigbeeRemoteCliCommandResponseReceivedEvent. The implementation includes the GObject definition, property accessors, and signal emission logic required to handle Zigbee remote CLI command responses.

feat(core): Add ZigbeeRemoteCliResponseEvent

---

hooks/clang-format-hooks/apply-format
hooks/clang-format-hooks/git-pre-commit-format

Our version of apply-format was old and not compatible with clang-format version 18+. This made committing very difficult if you had the hook installed.

chore(hooks): Update clang-format-hooks

---

api/c/test/CMakeLists.txt
config/cmake/modules/BDSAddCMockaTest.cmake
config/cmake/modules/BDSAddGLibTest.cmake
core/CMakeLists.txt
core/test/CMakeLists.txt

Stacked PRs:
* #19
* __->__#18
--- --- ---
This commit reorganizes cmake test targets to reduce complexity of the
main core/ CMakeLists file.

build: Reorganize most test targets

---

api/c/src/provider/device-service-property-provider.c
api/c/test/provider/device-service-property-provider-test.c

This change switches to case insensitive string comparison when reading boolean properties from the provider so clients using "True" or "TRUE" will properly map to true.
Refs: BARTON-263

fix(props): case insensitive bool props

---

core/src/subsystemManager.c

The MAP_FOREACH macro was causing segmentation faults when accessing
uninitialized stack variables in the subsystem manager.
To fix:
- Initialize all local variables in the macro and add a null check on the
map parameter to prevent crashes.
- Add null checks in all public functions that use MAP_FOREACH to enforce
proper API contracts and improve error handling.

fix: prevent segfaults in subsystemManager

---

NOTICE
config/cmake/DependencyVersions.cmake
config/cmake/modules/BCoreFindIncludeDir.cmake
docker/Dockerfile

Integrate the Fake Function Framework header-only library into our Docker build environment to enhance our mocking capabilities for unit tests.
- Add FFF installation to the Dockerfile
- Add FFF detection in CMake when tests are built
- Update NOTICE file with FFF attribution
- Update bcore_find_include to allow for an optional INCLUDE_LIST
This allows developers to use FFF's mocking capabilities alongside CMocka for more comprehensive unit testing.
Refs: BARTON-266

build: add fff to build environment

---

api/c/public/private/zigbeeClusters/illuminanceMeasurementCluster.h
api/c/public/private/zigbeeClusters/relativeHumidityMeasurementCluster.h
core/deviceDrivers/zigbee/zigbeeClusters/illuminanceMeasurementCluster.c
core/deviceDrivers/zigbee/zigbeeClusters/relativeHumidityMeasurementCluster.c
core/deviceDrivers/zigbee/zigbeeOccupancySensorDeviceDriver.c

Illuminance and humidity were being reported using the Zigbee encoded values rather than more user friendly units.
Refs: BARTON-268

fix(driver): correct values for illuminance and humidity

---

core/src/subsystems/matter/AccessRestrictionProvider.h
core/src/subsystems/matter/Matter.cpp
core/src/subsystems/matter/Matter.h

If the Matter SDK is compiled without Acccess Restriction List (ARL) support, then we must not try and enable related parts in our code or it wont build.

fix(matter): support ARL feature as optional

---

README.md
testing/py_test.sh

Some references to the original naming convention of `brtn` were lingering around in documentation and comments. Swap these usages out for the newer naming convention.

docs: replace old `brtn` usages

---

api/c/public/barton-core-properties.h
core/src/subsystems/matter/providers/default/DefaultCommissionableDataProvider.cpp

When the Matter SDK asks for the setup passcode, we need to return either a static one if we have not been commissioned or we need to generate a new one. This change will generate a new one if the property provider does not return one.
Refs: BARTON-269

feat(matter): Generate passcode if required

---

config/cmake/DependencyVersions.cmake

We removed the check for fff temporarily, turn the check back on.

build: turn fff dependency check back on

---

core/deviceDrivers/zigbee/zigbeeOccupancySensorDeviceDriver.c

Unused variable warning caused build failures on some targets.

fix: cleaned up an unused variable

---

core/src/event/deviceEventProducer.c
core/src/event/deviceEventProducer.h

Some usage of the original "deviceService" naming scheme persisted in deviceServiceEventProducer, refactor this to the "barton core" naming scheme.

refactor: deviceServiceClass

---

CMakeLists.txt
core/CMakeLists.txt

This commit adds support for setting the library version and SO version of libBartonCore. It also defines a "barton API version" that is an analog for namespace/platform version used in gir generation.

build: Set SO Version

---

.github/workflows/release.yaml
cog.toml
config/cocogitto/templates/remote_extended

This commit adds the ability to use cocogitto to automate versioning and releasing to Github. It:
1. Defines a custom template to use for CHANGELOG generation. This template is a variation of the built-in "remote" template file, but it handles BREAKING CHANGES separately and up-front. Template files are based on the Tera template engine https://keats.github.io/tera/
2. Adds a cog.toml file for configuring cocogitto cog commands.
3. Adds a Github workflow to use the cocogitto published action to generate a version and a changelog and then push it as a new github release. This workflow can only be run manually.

ci: Add cocogitto support to actions

---

.gitmessage
CONTRIBUTING.md

Need to be able to document features/fixes to the reference app without impacting semantic versioning of libBartonCore. This commit promotes `app` to a conventional commit type in our CONTRIBUTING doc and gitmessage hint.

chore: promote `app` to first class conventional commit type

---

core/src/subsystemManager.c
core/test/src/subsystems/subsystemManagerTest.c

Replace MAP_FOREACH macro usage in subsystemManager.c with explicit GHashTable iteration. This resolves a compiler warning about variable 'subsystemRegistration' being set but not used, caused by macro variable shadowing. Improves code maintainability and debuggability by removing macro indirection and making iteration logic explicit. No functional changes intended.
Also, remove the redundant `setOtaUpgradeDelay` function pointer assignments in `test_subsystemManagerSetOtaUpgradeDelay`.

refactor: remove MAP_FOREACH macro

---

CMakeLists.txt
config/cmake/options.cmake

The BCORE_PROVIDE_LIBS option existed to support an exisiting client of
Barton but is no longer needed, remove it.

build: remove BCORE_PROVIDE_LIBS option
